#!/bin/bash
if [ $# -ne 1 ]
then 
    echo "Nb d'arguments incorrect"
    exit 1
fi 

for i in $(seq $1) 
do 
    clear
    cowsay $i
    sleep 1
    if [ $i -eq $1 ]
    then 
        clear
        cowsay -T 'U ' "$i"
    fi
done